###
# Авторизация

POST {{baseUrl}}/users/sign
Content-Type: application/json

{
  "login": "test_1",
  "password": "123456"
}

###
# Выход - отмена авториазции для удаления токена

DELETE {{baseUrl}}/users/sign
X-Token: fcdd6bfd6fdc64a2fce5c87ccec7937f82d9e44f9319bbece0a187b702ac7895
Content-Type: application/json

###
# Свой профиль

GET {{baseUrl}}/users/self
X-Token: 622b6007c8a241209773d488fe9e59e464c71ed8d059e97fdcf781dc6d2972e9
Content-Type: application/json

###
