export const localize = {
	Магазин: { ru: 'Магазин', en: 'Shop', it: 'Negozio' },
	Главная: { ru: 'Главная', en: 'Home', it: 'Principale' },
	'В корзине': { ru: 'В корзине', en: 'In cart', it: 'Nel carrello' },
	Товар: { ru: 'Товар', en: 'Product', it: 'Prodotto' },
	Товара: { ru: 'Товара', en: 'Products', it: 'Prodotti' },
	Товаров: { ru: 'Товаров', en: 'Products', it: 'Prodotti' },
	Пусто: { ru: 'Пусто', en: 'Empty', it: 'Vuoto' },
	Перейти: { ru: 'Перейти', en: 'Go to', it: 'Passare' },
	Добавить: { ru: 'Добавить', en: 'Add', it: 'Aggiungere' },
	Закрыть: { ru: 'Закрыть', en: 'Close', it: 'Chiudere' },
	Корзина: { ru: 'Корзина', en: 'Cart', it: 'Cestino' },
	шт: { ru: 'шт', en: 'pc', it: 'pezzi' },
	Удалить: { ru: 'Удалить', en: 'Remove', it: 'Rimuovere' },
	Итого: { ru: 'Итого', en: 'Total', it: 'In totale' },
	'Страна производитель': {
		ru: 'Страна производитель',
		en: 'Country of origin',
		it: 'Paese produttore',
	},
	Категория: { ru: 'Категория', en: 'Category', it: 'Categoria' },
	'Год выпуска': {
		ru: 'Год выпуска',
		en: 'Year of release',
		it: 'Anno di produzione',
	},
	Цена: { ru: 'Цена', en: 'Price', it: 'Prezzo' },
	Загрузка: { ru: 'Загрузка', en: 'Loading', it: 'Caricamento' },
	'Не найдено': {
		ru: 'По данному адресу товаров на сайте не найдено',
		en: 'No products were found on the site at this address',
		it: 'Nessun prodotto è stato trovato sul sito a questo indirizzo',
	},
};
