let languages = {
  ru: {
    mainName: 'Магазин',
    inCart: 'В корзине:',
    buttonAdd: 'Добавить',
    openCart: 'Перейти',
    cart: 'Корзина',
    total: 'Итого:',
    closeCart: 'Закрыть',
    buttonDelete: 'Удалить',
    buttonToMain: 'Главная',
    country: 'Страна производитель:',
    category: 'Категория:',
    year: 'Год выпуска:',
    price: 'Цена: ',
    amount: 'шт',
  },
  eng: {
    mainName: 'Shop',
    inCart: 'In cart:',
    buttonAdd: 'Add',
    openCart: 'Open',
    cart: 'Cart',
    total: 'Total price:',
    closeCart: 'Close',
    buttonDelete: 'Delete',
    buttonToMain: 'Main page',
    country: 'Country:',
    category: 'Category:',
    year: 'Year:',
    price: 'Price: ',
    amount: 'pcs',
  },
};

export default languages;
